export const TRANSLATIONS_EN = 
{
  header_banner_text_1:"THE WALDOS LEGEND is the realization of a wacky project created by a talented and ambitious team. Passionate about blockchain, NFT and especially hemp cultivation, we are creating through the Waldos the first NFT project focused on CBD.",
  header_banner_text_2: "What is this legend that everyone is talking about in the metaverse? It is rooted in the story of the Waldos, dreamy young students full of ideals, like all of us, who sneaked out to meet up with friends and heard about a mysterious marijuana field abandoned by a coast guard who could not take care of it anymore. Thus, once a week at 4:20 p.m. after school, the Waldos met to go on an adventure to find this treasure... But in the end, they couldn't make it...",
  header_banner_text_3: " Finally, it is today, in the metaverse, that the legend reappears through THE WALDOS LEGEND and all Waldos can now search for the real abandoned field!",
  header_banner_text_4:"Thus, we offer Waldos access to truly exclusive advantages through this crazy project!",
  header_banner_text_5:"To do so, the TWL team already has all the cards in hand to satisfy the Waldos: the best supplier of flowers and CBD-derived products in Europe is already our trusted partner, ready to provide the best qualities. of the world to the Waldos to encourage them to find this treasure.",
  header_banner_text_6:"But before you run into the metaverse to get your hands on the One Piece of the Waldos, please read up on all aspects of THE WALDOS LEGEND!",

  community_title: "community",
  community_text_1:"Who can join the gang and how",
  community_text_2:"To be part of the Waldos, it\'s as simple as igniting the rocket: create a crypto wallet, deposit some money, snipe the launch and nab your NFT Waldos. Better than a lottery ticket, NFTs give access to real advantages.",
  community_text_3:"Why become a Waldos?",
  community_text_4:"Being part of the community is simply being part of a family. Not a club, a brotherhood and other bullshit, no. It\'s finding friends, passionate like us, who want to share their passions, their desires, their visions.",

  genesis_title: "GENESIS COLLECTION",
  genesis_text_1:"The collection consists of 420 NFTs. 420 unique and super cool Waldos that from the first level of rarity will provide amazing benefits !",
  genesis_text_2:"COMMON",
  genesis_text_3:"RARE",
  genesis_text_4:"MYTHIC",
  genesis_text_5:"30% discount on CBD products",
  genesis_text_6:"40% discount on CBD products",
  genesis_text_7:"50% discount on CBD products",
  genesis_text_8:"all THE WALDOS LEGEND merchandising",

  benefits_title: "CBD PRODUCT",
  benefits_text_1:"The Waldos will have exclusive access to the Waldos Shop: On the menu, varieties of high quality CBD products, tested and approved by the team to satisfy all desires.",
  benefits_text_2:"CBD flowers",
  benefits_text_3:"CBD resins",
  benefits_text_4:"Cosmetic products",
  benefits_text_5:"Products with therapeutic effects",
  benefits_text_6:"But also merchandising such as:",
  benefits_text_7:"A WALDOS brand, Hoodies, Tshirts, hats, etc.",
  benefits_text_8:"Accessories, lighters, grinders, stickers, ect",
  benefits_text_9:"And above all, Waldos aurton attractive prices depending on the rarity of their NFT ranging from 30% to 50% discount on all CBD flower and hash.",

  DAO_text_1:"The involvement of the Waldos is very important: being the holder of a Waldos will allow its owner to be able to give his opinion and influence the direction of THE WALDOS LEGEND project.",
  DAO_text_2:"The Waldos will be able to decide on the desired events for partnerships, collaborations. They will be able to decide on future projects: play 2 earn, second NFT collection, choice of variety of products for the community, etc.",
  DAO_text_3:"In short, be ambitious, original and we will make the community a real strength!",

  utility_text_title:"Utility",
  utility_text_1:"Owning an NFT will allow you to access the part reserved for the community on THE WALDOS LEGEND online shop and to be able to easily buy the best CBD products at unbeatable prices! You will also be able to buy the merchandising reserved for holders.",
  utility_text_2:"Thanks to a Waldos NFT, you will be able to benefit from limited access to events reserved for holders: Musical concerts, Festivals, Exhibitions, Meeting of communities",
  utility_text_3:"With strong and promising partners, we will offer holders access to super cool WLs and giveaways in unmissable projects in the blockchain! The choice of projects can even be decided in DAO by the community.",
  utility_text_4:"The Waldos have helped the community, so they deserve a reward! 30% of the NFT secondary market will be returned to the holders. The equivalent of a percentage of the profits generated by the Waldos Shops will be donated to the holders. Finally, only Waldos holders will be able to open a Waldos Legend franchise.",

  distribution_text_title:"Distribution",
  distribution_text_1:"We want to have a policy of transparency with the community. You can find a pie chart detailing the distribution of funds raised from the sale of the NFT collection.",

  team_text_title:"Team",
  team_text_1:"IRL painter and 2D/3D graphic designer in the blockchain, is the initiator of the project: NFT enthusiast and aficionados of the CBD, he is the creator of all the graphic charter and the NFT collection.",
  team_text_2:"Connoisseur of the Blockchain and NFT environment, CBD lover, is Head of communication: He is the one who will find us quality partners, very interesting collaborations to offer rewards to the Waldos. He also takes care of the management of social networks.",
  team_text_3:"Manager of an IRL company in the field of the sale of culture products, also specialized in CBD, is in charge of the products and logistics part. With a long experience in the CBD business, it is thanks to him that the Waldos have rare and qualitative products.",
  team_text_4:"Crypto and NFT veteran in the blockchain, founder of the French-speaking community ''Les Collectionneurs NFT'', is a major asset in THE WALDOS LEGEND. The knowledge and the network it provides are indispensable in all the processes we encounter in the project.",
  team_text_5:"Talented blockchain developer, is the magician who brings THE WALDOS LEGEND project to life thanks to the smart contract, the legal integration with NFTs, the proper functioning of the ecosystem.",

  next_text_title:"Next",
  next_text_1:"We have big (well, reasonable) ambitions for the future In the world of Waldos, we intend to take into consideration the expectations of the community:",
  next_text_2:"Indeed, the DAO will help define future projects for THE WALDOS LEGEND! We are listening!"


}